services:
  - type: web
    name: rice-leaf-api
    env: python
    build:
      command: pip install -r requirements.txt
      startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10